### ISSUE TITLE
Plugin does not work on Linux

### ISSUE THREAD

**Issue by D33pfield** [Thurion/EDSM-RSE-for-EDMC#49]
Error:
```
loading plugin EDSM-RSE from "/home/deepfield/.local/share/EDMarketConnector/plugins/EDSM-RSE/load.py"
Traceback (most recent call last):
  File "/home/deepfield/Games/edmc/plug.py", line 193, in load_plugins
    found.append(Plugin(name, os.path.join(config.plugin_dir, name, 'load.py')))
  File "/home/deepfield/Games/edmc/plug.py", line 94, in __init__
    ('.py', 'r', imp.PY_SOURCE))
  File "/home/deepfield/.local/share/EDMarketConnector/plugins/EDSM-RSE/load.py", line 34, in <module>
    from RseData import RseData, EliteSystem
  File "/home/deepfield/.local/share/EDMarketConnector/plugins/EDSM-RSE/RseData.py", line 25, in <module>
    import psycopg2
  File "/home/deepfield/.local/share/EDMarketConnector/plugins/EDSM-RSE/psycopg2/__init__.py", line 50, in <module>
    from psycopg2._psycopg import (                     # noqa
ImportError: No module named _psycopg
```

**Comment by Thurion** [comment]
I know.
The postgreSQL library is a binary and we only bundled it with the Windows version of it.

Do you run it from source?
You could try to add the postgreSQL driver yourself as described here: https://pypi.org/project/psycopg2/

There is also a web based API in the works which means we wouldn't need the postgreSQL anymore. But I don't have an ETA on that.

**Comment by D33pfield** [comment]
> You could try to add the postgreSQL driver yourself as described here: https://pypi.org/project/psycopg2/

That seems to have done it. Thank you!
