### ISSUE TITLE
error as of EDMC v. 5.6.0

### ISSUE THREAD

**Issue by RapidfireCRH** [Thurion/EDSM-RSE-for-EDMC#68]
2022-11-28 22:13:02.779 UTC - ERROR - 14116:20016:20016 plug.Plugin.__init__:62: : Failed for Plugin "EDSM-RSE-for-EDMC-development"
Traceback (most recent call last):
  File "plug.pyc", line 53, in __init__
  File "C:\Users\rapid\AppData\Local\EDMarketConnector\plugins\EDSM-RSE-for-EDMC-development\load.py", line 147, in plugin_start3
    plugin_start(plugin_dir)
  File "C:\Users\rapid\AppData\Local\EDMarketConnector\plugins\EDSM-RSE-for-EDMC-development\load.py", line 132, in plugin_start
    this.enabled = check_transmission_options()
  File "C:\Users\rapid\AppData\Local\EDMarketConnector\plugins\EDSM-RSE-for-EDMC-development\load.py", line 113, in check_transmission_options
    eddn = (config.get_int("output") & config.OUT_SYS_EDDN) == config.OUT_SYS_EDDN
AttributeError: 'WinConfig' object has no attribute 'OUT_SYS_EDDN'
2022-11-28 22:13:02.783 UTC - ERROR - 14116:20016:20016 plug.load_plugins:159: Failure loading found Plugin "EDSM-RSE-for-EDMC-development"
Traceback (most recent call last):
  File "plug.pyc", line 157, in load_plugins
  File "plug.pyc", line 53, in __init__
  File "C:\Users\rapid\AppData\Local\EDMarketConnector\plugins\EDSM-RSE-for-EDMC-development\load.py", line 147, in plugin_start3
    plugin_start(plugin_dir)
  File "C:\Users\rapid\AppData\Local\EDMarketConnector\plugins\EDSM-RSE-for-EDMC-development\load.py", line 132, in plugin_start
    this.enabled = check_transmission_options()
  File "C:\Users\rapid\AppData\Local\EDMarketConnector\plugins\EDSM-RSE-for-EDMC-development\load.py", line 113, in check_transmission_options
    eddn = (config.get_int("output") & config.OUT_SYS_EDDN) == config.OUT_SYS_EDDN
AttributeError: 'WinConfig' object has no attribute 'OUT_SYS_EDDN'

**Comment by RapidfireCRH** [comment]
Was working fine before the update of EDMC

**Comment by RapidfireCRH** [comment]
I think the python version for 5.6.0 got updated, this may be the cause

**Comment by Thurion** [comment]
Can you test it please? I pushed the changes onto the development branch.
The issue was that some configuration changed and not the Python version.
