### ISSUE TITLE
Not working on EDMC 5.10.1+5419e2e

### ISSUE THREAD

**Issue by KroshkaRoo** [Thurion/EDSM-RSE-for-EDMC#69]
Subj

**Comment by Amiganer** [comment]
Is it possible to get a few more informations on this, please.

**Comment by KroshkaRoo** [comment]
![изображение](https://github.com/Thurion/EDSM-RSE-for-EDMC/assets/52600064/92297dc3-8c30-4dea-8fab-984fbd927ba8)

**Comment by KroshkaRoo** [comment]
Folder structure is correct

**Comment by KroshkaRoo** [comment]
![изображение](https://github.com/Thurion/EDSM-RSE-for-EDMC/assets/52600064/d822d5c0-3780-4544-ad7b-94389b0727f5)

**Comment by KroshkaRoo** [comment]
```
2024-02-18 09:39:53.232 UTC - INFO - 9380:6052:6052 plug.Plugin.__init__:65: loading plugin "EDSM-RSE-for-EDMC-development" from "C:\Users\KroshkaRoo\AppData\Local\EDMarketConnector\plugins\EDSM-RSE-for-EDMC-development\load.py"
2024-02-18 09:39:53.278 UTC - ERROR - 9380:6052:6052 plug.Plugin.__init__:83: : Failed for Plugin "EDSM-RSE-for-EDMC-development"
Traceback (most recent call last):
  File "plug.pyc", line 74, in __init__
  File "C:\Users\KroshkaRoo\AppData\Local\EDMarketConnector\plugins\EDSM-RSE-for-EDMC-development\load.py", line 147, in plugin_start3
    plugin_start(plugin_dir)
  File "C:\Users\KroshkaRoo\AppData\Local\EDMarketConnector\plugins\EDSM-RSE-for-EDMC-development\load.py", line 132, in plugin_start
    this.enabled = check_transmission_options()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\KroshkaRoo\AppData\Local\EDMarketConnector\plugins\EDSM-RSE-for-EDMC-development\load.py", line 113, in check_transmission_options
    eddn = (config.get_int("output") & config.OUT_SYS_EDDN) == config.OUT_SYS_EDDN
                                       ^^^^^^^^^^^^^^^^^^^
AttributeError: 'WinConfig' object has no attribute 'OUT_SYS_EDDN'
2024-02-18 09:39:53.281 UTC - INFO - 9380:6052:6052 plug.Plugin.__init__:86: plugin EDSM-RSE-for-EDMC-development disabled
2024-02-18 09:39:53.282 UTC - ERROR - 9380:6052:6052 plug._load_found_plugins:203: Failure loading found Plugin "EDSM-RSE-for-EDMC-development"
Traceback (most recent call last):
  File "plug.pyc", line 200, in _load_found_plugins
  File "plug.pyc", line 74, in __init__
  File "C:\Users\KroshkaRoo\AppData\Local\EDMarketConnector\plugins\EDSM-RSE-for-EDMC-development\load.py", line 147, in plugin_start3
    plugin_start(plugin_dir)
  File "C:\Users\KroshkaRoo\AppData\Local\EDMarketConnector\plugins\EDSM-RSE-for-EDMC-development\load.py", line 132, in plugin_start
    this.enabled = check_transmission_options()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\KroshkaRoo\AppData\Local\EDMarketConnector\plugins\EDSM-RSE-for-EDMC-development\load.py", line 113, in check_transmission_options
    eddn = (config.get_int("output") & config.OUT_SYS_EDDN) == config.OUT_SYS_EDDN
                                       ^^^^^^^^^^^^^^^^^^^
AttributeError: 'WinConfig' object has no attribute 'OUT_SYS_EDDN'
```

**Comment by Thurion** [comment]
Try this version please: https://github.com/Thurion/EDSM-RSE-for-EDMC/releases/tag/ver_1.4.2

**Comment by KroshkaRoo** [comment]
Work fine! Thank you!
