### ISSUE TITLE
Initialization Error under 5.11.0+f93485e

### ISSUE THREAD

**Issue by traveller42** [Thurion/EDSM-RSE-for-EDMC#70]
After updating to version 5.11.0+f93485e of EDMC, EDSM-RSE is not showing in the window.

I removed the installation in the plugins directory, stopped EDMC, installed a fresh download from GitHub, and restarted EDMC with no impact to this state.

Reviewing the logs, I see the following:L
```
2024-06-09 14:59:02.984 UTC - ERROR - 2716:16232:16232 plug.Plugin.get_app:129: Failed for Plugin "EDSM-RSE"
Traceback (most recent call last):
  File "plug.pyc", line 111, in get_app
  File "C:\Users\Clark\AppData\Local\EDMarketConnector\plugins\EDSM-RSE\load.py", line 329, in plugin_app
    this.unconfirmedSystem = RseHyperlinkLabel(this.frame, compound=tk.RIGHT, popup_copy=True)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Clark\AppData\Local\EDMarketConnector\plugins\EDSM-RSE\load.py", line 93, in __init__
    self.menu.add_command(label=_("Ignore once"), command=self.ignore_once)
    ^^^^^^^^^
AttributeError: 'RseHyperlinkLabel' object has no attribute 'menu'
```
Included as it might be needed:
```
2024-06-09 14:59:02.776 UTC - DEBUG - 2716:16232:16232 <plugins>.EDSM-RSE.load.plugin_start:150: Debug messages are enabled.
2024-06-09 14:59:02.779 UTC - DEBUG - 2716:16232:16232 <plugins>.EDSM-RSE.load.plugin_start:151: Python Version: 3.11.9 (tags/v3.11.9:de54cf5, Apr  2 2024, 10:00:00) [MSC v.1938 32 bit (Intel)].
```

**Comment by Thurion** [comment]
I changed the behavior of the plugin but it's currently only available on the development branch.
Can you download https://raw.githubusercontent.com/Thurion/EDSM-RSE-for-EDMC/development/load.py and copy/move it into the RSE plugin's folder, please? Overwrite the old file.

**Comment by traveller42** [comment]
Replaced the file on my system with the one linked, and I now have the expected section in the EDMC window.

I did not have time to log into the game to verify operation, but initialization appears to be working as desired.

**Comment by Thurion** [comment]
Made a new release so it's easier to find and use: https://github.com/Thurion/EDSM-RSE-for-EDMC/releases/tag/ver_1.4.3
